### ISSUE TITLE
additions added to gmk_sym

### ISSUE THREAD

**Issue by drforbin** [lepton-eda/lepton-eda#152]
Added functionality to gmk_sym.
Please see commit ac32b912babb1eb3b7eff79bea0788aa80e2773a

**Comment by vzh** [comment]
@drforbin Please look at #154. Instead of pointing out every bit I didn't like in your additions, I just  squashed your commits and added several changes. Please note the following:
- C++ comment style `//` should be avoided
- Please don't insert your name anywhere in the code, it's enough to have it in the changes section, and in git commit itself (`git blame` will show you all author names, anyways) ;-)
- Please be more careful and avoid trailing whitespaces

TBD things I have not modified there, and hope you'll fix them yourself:
- README and your new *.txt file are not included into the distribution, please add them to the `EXTRA_DIST` variables in appropriate places
- I am not sure README is needed at all, what is it for? It would be better to include its info into the commit message and wiki. WDYT? And by the way, what is *interved edge*?
- a more appropriate name for `new_version_example.txt` would be desirable, since the last utility version will not be always a new one :-)

Please fix those above, thanks!
