### ISSUE TITLE
Document compability

### ISSUE THREAD

**Issue by spth** [lepton-eda/lepton-eda#653]
I am currently using gschem 1.8.2, the latest gschem version in Debian. Apparently the geda-gschem / geda-gaf maintainer moved to lepton, so (like probably many pre-fork gschem users) wonder:

* Will I be able to work with old gEDA files using lepton (I guess yes)?
* Will I be able to work with past-fork gEDA files using lepton (I have no idea)?
* Will I be able to work with lepton files using post-fork gEDA (I have no idea)?

It would be good to have a section on compability in the README file.

**Comment by graahnul-grom** [comment]
Lepton EDA and gEDA uses the same file format, nothing has changed
in this regard, so
1) yes
2) yes
3) yes

Thank you for the good suggestion, we will add notes on compatibility
to the README file.

**Comment by vzh** [comment]
One small addition to what @graahnul-grom has already said.  So far, we supported gEDA file format and are planning to do so in future since there are lots of symbols/schematics created using it.  If there will be some additions on the `geda-gaf` side (e.g., wrt attributes, or new file format version, and such), it depends on users of Lepton, on you, to point us to what you think is not supported but should be.  The same is true wrt other features in `geda-gaf` Lepton may not have.  We are not able to fully keep track of that project, so again, we depend on our users here and need your feedback.
